interface WordCategories {
  [category: string]: string[];
}

const wordCategories: WordCategories = {
  animals: [
    "polar bear",
    "tiger",
    "elephant",
    "giraffe",
    "penguin",
    "dolphin",
    "eagle",
    "kangaroo",
    "cheetah",
    "octopus",
    "rhinoceros",
    "lion",
    "zebra",
    "hippopotamus",
    "polar bear",
    "crocodile",
    "gorilla",
    "panda",
    "koala",
    "squirrel",
    "ostrich",
    "gazelle",
    "leopard",
    "buffalo",
    "peacock",
    "sloth"
  ],
  countries: [
    "canada",
    "brazil",
    "japan",
    "australia",
    "france",
    "germany",
    "india",
    "russia",
    "egypt",
    "mexico",
    "china",
    "italy",
    "spain",
    "south africa",
    "argentina",
    "netherlands",
    "united kingdom",
    "switzerland",
    "thailand",
    "turkey",
    "norway",
    "sweden",
    "new zealand",
    "greece",
    "portugal",
  ],

  fruits: [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "pineapple",
    "watermelon",
    "kiwi",
    "mango",
    "grape",
    "peach",
    "coconut",
    "cherry",
    "pear",
    "lemon",
    "raspberry",
    "blueberry",
    "apricot",
    "plum",
    "fig",
    "avocado",
    "cantaloupe",
    "blackberry",
    "pomegranate",
    "lychee",
    "passion fruit",
  ],

  sports: [
    "soccer",
    "basketball",
    "tennis",
    "swimming",
    "baseball",
    "golf",
    "volleyball",
    "rugby",
    "cycling",
    "wrestling",
    "boxing",
    "hockey",
    "skiing",
    "surfing",
    "gymnastics",
    "cricket",
    "sailing",
    "fencing",
    "karate",
    "martial arts",
    "badminton",
    "table tennis",
    "rowing",
    "diving",
    "skateboarding",
  ],

  colors: [
    "red",
    "blue",
    "green",
    "yellow",
    "purple",
    "orange",
    "pink",
    "brown",
    "black",
    "white",
    "gray",
    "cyan",
    "magenta",
    "turquoise",
    "lavender",
    "teal",
    "maroon",
    "gold",
    "silver",
    "bronze",
    "beige",
    "indigo",
    "olive",
    "salmon",
    "violet",
  ],

};

export default wordCategories;
