interface WordCategories {
  [category: string]: string[];
}

const wordCategories: WordCategories = {
  animals: [
    "tiger",
    "elephant",
    "giraffe",
    "penguin",
    "dolphin",
    "eagle",
    "kangaroo",
    "cheetah",
    "octopus",
    "rhinoceros",
    "lion",
    "zebra",
    "hippopotamus",
    "polar bear",
    "crocodile",
    "gorilla",
    "panda",
    "koala",
    "squirrel",
    "ostrich",
    "gazelle",
    "leopard",
    "buffalo",
    "peacock",
    "sloth",
  ],
  countries: [
    "canada",
    "brazil",
    "japan",
    "australia",
    "france",
    "germany",
    "india",
    "russia",
    "egypt",
    "mexico",
    "china",
    "italy",
    "spain",
    "south africa",
    "argentina",
    "netherlands",
    "united kingdom",
    "switzerland",
    "thailand",
    "turkey",
    "norway",
    "sweden",
    "new zealand",
    "greece",
    "portugal",
  ],

  fruits: [
    "apple",
    "banana",
    "orange",
    "strawberry",
    "pineapple",
    "watermelon",
    "kiwi",
    "mango",
    "grape",
    "peach",
    "coconut",
    "cherry",
    "pear",
    "lemon",
    "raspberry",
    "blueberry",
    "apricot",
    "plum",
    "fig",
    "avocado",
    "cantaloupe",
    "blackberry",
    "pomegranate",
    "lychee",
    "passion fruit",
  ],

  professions: [
    "doctor",
    "engineer",
    "teacher",
    "artist",
    "chef",
    "pilot",
    "lawyer",
    "musician",
    "athlete",
    "scientist",
    "actor",
    "architect",
    "dentist",
    "writer",
    "photographer",
    "journalist",
    "veterinarian",
    "nurse",
    "electrician",
    "plumber",
    "psychologist",
    "biologist",
    "chemist",
    "geologist",
    "mathematician",
  ],

  sports: [
    "soccer",
    "basketball",
    "tennis",
    "swimming",
    "baseball",
    "golf",
    "volleyball",
    "rugby",
    "cycling",
    "wrestling",
    "boxing",
    "hockey",
    "skiing",
    "surfing",
    "gymnastics",
    "cricket",
    "sailing",
    "fencing",
    "karate",
    "martial arts",
    "badminton",
    "table tennis",
    "rowing",
    "diving",
    "skateboarding",
  ],

  colors: [
    "red",
    "blue",
    "green",
    "yellow",
    "purple",
    "orange",
    "pink",
    "brown",
    "black",
    "white",
    "gray",
    "cyan",
    "magenta",
    "turquoise",
    "lavender",
    "teal",
    "maroon",
    "gold",
    "silver",
    "bronze",
    "beige",
    "indigo",
    "olive",
    "salmon",
    "violet",
  ],

  planets: [
    "mercury",
    "venus",
    "earth",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "ceres",
    "haumea",
    "makemake",
    "eris",
    "sedna",
    "orcus",
    "quaoar",
    "varuna",
    "ixion",
    "deucalion",
    "eurydome",
    "herse",
    "euphrosyne",
    "pallas",
    "juno",
    "vesta",
  ],

  vegetables: [
    "carrot",
    "potato",
    "tomato",
    "broccoli",
    "spinach",
    "cucumber",
    "eggplant",
    "lettuce",
    "onion",
    "pepper",
    "cabbage",
    "pumpkin",
    "zucchini",
    "radish",
    "turnip",
    "artichoke",
    "celery",
    "asparagus",
    "garlic",
    "beetroot",
    "brussels sprouts",
    "cauliflower",
    "kale",
    "rutabaga",
    "sweet potato",
  ],

  instruments: [
    "guitar",
    "piano",
    "violin",
    "trumpet",
    "flute",
    "drum",
    "saxophone",
    "cello",
    "harp",
    "clarinet",
    "accordion",
    "banjo",
    "trombone",
    "harmonica",
    "xylophone",
    "bagpipes",
    "tuba",
    "oboe",
    "ukulele",
    "accordion",
    "mandolin",
    "theremin",
    "djembe",
    "sitar",
    "kalimba",
  ],

  elements: [
    "hydrogen",
    "oxygen",
    "carbon",
    "nitrogen",
    "sodium",
    "potassium",
    "calcium",
    "iron",
    "copper",
    "zinc",
    "helium",
    "chlorine",
    "magnesium",
    "sulfur",
    "phosphorus",
    "neon",
    "argon",
    "aluminum",
    "silicon",
    "fluorine",
    "gold",
    "silver",
    "mercury",
    "lead",
    "tin",
  ],
};

export default wordCategories;
